apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micheal-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: a02a0628bff0e4c54ade76c1c897f4f8-508638849.us-east-2.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: micheal-web-service
            port:
              number: 80  # Changed from 'port: 80' to 'port: {number: 80}'
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: micheal-back-service
            port:
              number: 3129  # Changed from 'port: 3129' to 'port: {number: 3129}'
