apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: micheal-back-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: micheal-back-deployment  # Target your backend deployment
  minReplicas: 0
  maxReplicas: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Scale when CPU usage > 50%
