apiVersion: apps/v1
kind: Deployment
metadata:
  name: micheal-back-deployment-green
  labels:
    app: micheal-back-green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: micheal-back-green
  template:
    metadata:
      labels:
        app: micheal-back-green
    spec:
      volumes:
        - name: aws-credentials-volume
          secret:
            secretName: aws-credentials
        - name: app-credentials-volume
          emptyDir: {}

      initContainers:
        - name: setup-aws-credentials
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - "echo 'Copying AWS credentials...';
              cp /secrets/access_key /secrets/secret_key /app-credentials/;
              ls -l /app-credentials/;
              echo 'Init container completed successfully'"
          volumeMounts:
            - name: aws-credentials-volume
              mountPath: "/secrets"
              readOnly: true
            - name: app-credentials-volume
              mountPath: "/app-credentials"

      containers:
        - name: micheal-back
          image: amazingatul/ecom-backend:prodv1
          ports:
            - containerPort: 3129
            - containerPort: 9100  # 🔹 Prometheus metrics port
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret_key
            - name: AWS_REGION
              value: "us-east-1"
            - name: PROMETHEUS_METRICS_PORT  # 🔹 Expose this if required
              value: "9100"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: micheal-back-green-service
spec:
  selector:
    app: micheal-back-green
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3129
    - name: metrics  # 🔹 Prometheus scraping endpoint
      protocol: TCP
      port: 9100
      targetPort: 9100
