apiVersion: apps/v1
kind: Deployment
metadata:
  name: micheal-back-deployment-green
  labels:
    app: micheal-back-green
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: micheal-back-green
  template:
    metadata:
      labels:
        app: micheal-back-green
    spec:
      volumes:
        - name: aws-credentials-volume
          secret:
            secretName: aws-credentials
        - name: app-credentials-volume
          emptyDir: {}
        - name: app-logs
          emptyDir: {}

      initContainers:
        - name: setup-aws-credentials
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - "echo 'Copying AWS credentials...';
              cp /secrets/access_key /secrets/secret_key /app-credentials/;
              ls -l /app-credentials/;
              echo 'Init container completed successfully'"
          volumeMounts:
            - name: aws-credentials-volume
              mountPath: "/secrets"
              readOnly: true
            - name: app-credentials-volume
              mountPath: "/app-credentials"

      containers:
        - name: micheal-back
          image: amazingatul/ecom-backend:prodv1
          ports:
            - containerPort: 3129
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret_key
            - name: AWS_REGION
              value: "us-east-1"
          volumeMounts:
            - name: app-credentials-volume
              mountPath: "/app-credentials"
              readOnly: true
            - name: app-logs
              mountPath: "/var/log/app"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

          # Probes Added Here!
          startupProbe:
            httpGet:
              path: /healthz
              port: 3129
            failureThreshold: 10
            periodSeconds: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 3129
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /ready
              port: 3129
            periodSeconds: 10

        - name: fluentd-sidecar
          image: fluent/fluentd:v1.17.1-debian-1.1
          volumeMounts:
            - name: app-logs
              mountPath: "/var/log/app"
          resources:
            limits:
              cpu: "0.5"  
              memory: "512Mi"  
            requests:
              cpu: "0.2"  
              memory: "256Mi"
