apiVersion: apps/v1
kind: Deployment
metadata:
  name: micheal-back-deployment-green
  labels:
    app: micheal-back-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: micheal-back-green
  template:
    metadata:
      labels:
        app: micheal-back-green
    spec:
      containers:
        - name: micheal-back
          image: amazingatul/ecom-backend:prodv1  # UPDATED IMAGE
          imagePullPolicy: Always  
          ports:
            - containerPort: 3129
          resources:
            requests:
              cpu: "500m"  
              memory: "512Mi"  
            limits:
              cpu: "1000m"  
              memory: "1024Mi" 
      restartPolicy: Always  
